language: ruby
services:
  - mongodb
before_install:
  - gem update --system
  - gem install bundler
  - bundle update --bundler
after_script:
  - bundle exec rubocop
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
